#!/bin/sh
ssh -t -t -p 52014 dev@218.232.7.30 <<EOF
    cd ~/test/sample-project		
    git pull origin master
    npm install
    npm i -g @nestjs/cli
    npm install -g pm2 typescript ts-node
    pm2 install typescript
    pm2 start dist/main.js
    exit
EOF