#!/bin/sh
ssh ubuntu@3.34.45.32 <<EOF
    cd ~/test/sample-project		
    git pull origin master
    npm install
    npm i -g @nestjs/cli
    npm install -g pm2
    pm2 restart dist/main.js
    exit
EOF