#!/bin/sh
<<EOF
    git pull origin master
    npm install
    npm i -g @nestjs/cli
    npm i -g pm2 typescript ts-node
    pm2 install typescript
    pm2 list
    pm2 kill
    pm2 start dist/main.js
    exit
EOF